### ISSUE TITLE
Request publishing the extension to Microsoft Edge Add-ons Store

### ISSUE THREAD

**Issue by Ein-Tim** [MrWillCom/github-enhancing#1]
Hey @MrWillCom 👋🏻

First of all thanks for your amazing work in [MrWillCom/github-dark-mode](https://github.com/MrWillCom/github-dark-mode)!

But now I have a question about this project: 
Will you also release this for Microsoft Edge (Chrome)? That would be so great! 
Thanks!

**Comment by MrWillCom** [comment]
Okay! It's now in review. 😄 

![A screenshot of Microsoft Edge Partner Center](https://user-images.githubusercontent.com/47271684/102708517-ce861a00-42de-11eb-8337-ae5c18e87710.png)

**Comment by Ein-Tim** [comment]
I've opened #2 and can confirm that the Extension is in the Store and working. 
Thank you so much for publishing it there so fast!

**Comment by MrWillCom** [comment]
Hey! It's now officially available in Microsoft Edge Add-ons Store: https://microsoftedge.microsoft.com/addons/detail/ogkeblbkmfddfmdmaegnfcnpnjjijold 🎉

**Comment by Ein-Tim** [comment]
Thanks @MrWillCom 

If you like to you can merge #2 so that also other users see the option to download the extension form the Microsoft Store. 😄
